module.exports = [
  {
    nis: 1001,
    name: "Aditya Hamzah",
    class_id: 1,
    room_id: 6,
    district: "JAKARTA",
    birthplace: "JAKARTA",
    birthdate: "12/22/2005",
    guardian: "SUPARMI",
  },
  {
    nis: 1002,
    name: "Agung Putra Wirana",
    class_id: 1,
    room_id: 4,
    district: "JAKARTA SELATAN",
    birthplace: "JAKARTA",
    birthdate: "02/26/2006",
    guardian: "TRIANAH",
  },
  {
    nis: 1003,
    name: "Ahmad Fahmi Ramadhan",
    class_id: 1,
    room_id: 6,
    district: "JAKARTA",
    birthplace: "JAKARTA",
    birthdate: "09/26/2006",
    guardian: "LUKMUN",
  },
  {
    nis: 1004,
    name: "Bondan Ramadhan",
    class_id: 1,
    room_id: 8,
    district: "JAKARTA",
    birthplace: "JAKARTA",
    birthdate: "10/4/2005",
    guardian: "WWARDOYO",
  },
  {
    nis: 1005,
    name: "Daffa Nailul Ramadhan",
    class_id: 1,
    room_id: 7,
    district: "JAWA BARAT",
    birthplace: "TANGERANG",
    birthdate: "10/5/2005",
    guardian: "SUSIAH",
  },
  {
    nis: 1006,
    name: "Davi Permana",
    class_id: 1,
    room_id: 6,
    district: "JAKARTA SELATAN",
    birthplace: "JAKARTA",
    birthdate: "9/10/2005",
    guardian: "YUSNIAH",
  },
  {
    nis: 1007,
    name: "Fandi Akhmad Akbar",
    class_id: 1,
    room_id: 5,
    district: "TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "3/27/2006",
    guardian: "DEWI SUCI ASTUTI",
  },
  {
    nis: 1008,
    name: "Farish Jam'an",
    class_id: 1,
    room_id: 6,
    district: "TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "12/14/2005",
    guardian: "DISMAN",
  },
  {
    nis: 1009,
    name: "Habib Rizki Fadilah",
    class_id: 1,
    room_id: 8,
    district: "TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "3/18/2006",
    guardian: "SYARIFUDIN",
  },
  {
    nis: 1010,
    name: "Hudan Muhammad Rizki",
    class_id: 1,
    room_id: 5,
    district: "BOGOR",
    birthplace: "BOGOR",
    birthdate: "5/25/2006",
    guardian: "RETRI",
  },
  {
    nis: 1011,
    name: "Jaka Ghazy Nabil",
    class_id: 1,
    room_id: 3,
    district: "BEKASI",
    birthplace: "BEKASI",
    birthdate: "3/20/2006",
    guardian: "BENI HENDIK",
  },
  {
    nis: 1012,
    name: "Maulana Adnan Atthouriq",
    class_id: 1,
    room_id: 5,
    district: "JAKARTA",
    birthplace: "JAKARTA",
    birthdate: "12/3/2005",
    guardian: "SARAH",
  },
  {
    nis: 1013,
    name: "Mohammad Fathir Pahlevi",
    class_id: 1,
    room_id: 5,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "8/15/2006",
    guardian: "MURNIASIH",
  },
  {
    nis: 1014,
    name: "Mufid Nailar Ridho",
    class_id: 1,
    room_id: 8,
    district: "JAKARTA SELATAN",
    birthplace: "JAKARTA",
    birthdate: "11/1/2006",
    guardian: "SRI ASTUTI",
  },
  {
    nis: 1015,
    name: "Muhamad Kautsar Fayad",
    class_id: 1,
    room_id: 3,
    district: "TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "1/4/2006",
    guardian: "NURHAYATI",
  },
  {
    nis: 1016,
    name: "Muhammad Al Haikari",
    class_id: 1,
    room_id: 4,
    district: "JAKARTA PUSAT",
    birthplace: "JAKARTA",
    birthdate: "5/27/2006",
    guardian: "NUR",
  },
  {
    nis: 1017,
    name: "Muhammad Dhanny Mulyana",
    class_id: 1,
    room_id: 8,
    district: "PALEMBANG",
    birthplace: "PALEMBANG",
    birthdate: "1/1/2006",
    guardian: "AFRINNA.Z",
  },
  {
    nis: 1018,
    name: "Muhammad Falih Mahdi Romadhon",
    class_id: 1,
    room_id: 7,
    district: "TANGERANG",
    birthplace: "TANGERANG SEL",
    birthdate: "10/16/2006",
    guardian: "LISNA WATI",
  },
  {
    nis: 1019,
    name: "Muhammad Iqrar Fathir",
    class_id: 1,
    room_id: 4,
    district: "BEKASI",
    birthplace: "BEKASI",
    birthdate: "12/10/2006",
    guardian: "SITI SOPIAH",
  },
  {
    nis: 1020,
    name: "Muhammad Rayyan Al-Mutawakkil",
    class_id: 1,
    room_id: 6,
    district: "JAKARTA",
    birthplace: "JAKARTA",
    birthdate: "2/3/2006",
    guardian: "ABU BAKAR.D",
  },
  {
    nis: 1021,
    name: "Muhammad Ridwan",
    class_id: 1,
    room_id: 6,
    district: "JAKARTA SELATAN",
    birthplace: "JAKARTA",
    birthdate: "2/13/2006",
    guardian: "SYARIFUDIN",
  },
  {
    nis: 1022,
    name: "Muhammad Shodqi Ramadhan",
    class_id: 1,
    room_id: 4,
    district: "DEPOK",
    birthplace: "DEPOK",
    birthdate: "9/25/2006",
    guardian: "FITRI",
  },
  {
    nis: 1023,
    name: "Nandar Shello Pratama",
    class_id: 1,
    room_id: 4,
    district: "KARAWANG",
    birthplace: "KARANGANYAR",
    birthdate: "3/7/2006",
    guardian: "SUNARMAN",
  },
  {
    nis: 1024,
    name: "Nick Metin Zen",
    class_id: 1,
    room_id: 6,
    district: "TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "8/27/2005",
    guardian: "CAHYAWATI",
  },
  {
    nis: 1025,
    name: "Rasyid Adam Alfatih",
    class_id: 1,
    room_id: 5,
    district: "TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "1/7/2006",
    guardian: "YULIANINGSIH",
  },
  {
    nis: 1026,
    name: "Reza Septian Andriansyah",
    class_id: 1,
    room_id: 3,
    district: "KARAWANG",
    birthplace: "KARAWANG",
    birthdate: "9/5/2006",
    guardian: "SANIH",
  },
  {
    nis: 1027,
    name: "Rio Albuchori",
    class_id: 1,
    room_id: 6,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "11/9/2005",
    guardian: "TANGERANG",
  },
  {
    nis: 1028,
    name: "Romy Ibnu Arifin",
    class_id: 1,
    room_id: 4,
    district: "SUBANG",
    birthplace: "SUBANG",
    birthdate: "1/28/2006",
    guardian: "DIMYATI",
  },
  {
    nis: 1029,
    name: "Solekhudin Al Gifary",
    class_id: 1,
    room_id: 4,
    district: "TEGAL",
    birthplace: "TEGAL",
    birthdate: "5/5/2006",
    guardian: "SRIWIDODO",
  },
  {
    nis: 1030,
    name: "Syahrul Rahmadani",
    class_id: 1,
    room_id: 4,
    district: "TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "10/16/2005",
    guardian: "IKAH",
  },
  {
    nis: 1031,
    name: "Taufik Qurahman Sholeh",
    class_id: 1,
    room_id: 3,
    district: "JAKARTA SELATAN",
    birthplace: "JAKARTA",
    birthdate: "10/20/2005",
    guardian: "SUMSINAR",
  },
  {
    nis: 1032,
    name: "Wiarrizqy Primadani Muthohar",
    class_id: 1,
    room_id: 3,
    district: "TANGERANG SELATAN",
    birthplace: "JAKARTA",
    birthdate: "10/24/2004",
    guardian: "SRI REJEKI",
  },
  {
    nis: 1033,
    name: "Zybrila Ahmad Izharul Haq",
    class_id: 1,
    room_id: 3,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG SELATAN",
    birthdate: "2/9/2006",
    guardian: "KOKOM",
  },
  {
    nis: 1034,
    name: "MUHAMMAD RIFKIAVANSYAH",
    class_id: 1,
    room_id: 3,
    district: "TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "4/5/2006",
    guardian: "WAHID",
  },
  {
    nis: 1035,
    name: "PAULINUS LEKAN",
    class_id: 1,
    room_id: 7,
    district: "MENTAWAI",
    birthplace: "BUTTUI",
    birthdate: "8/21/2004",
    guardian: "LIANNA",
  },
  {
    nis: 1036,
    name: "Afriza Bagas Pahlevi",
    class_id: 2,
    room_id: 6,
    district: "TANGERANG",
    birthplace: "JAKARTA",
    birthdate: "8/29/2005",
    guardian: "HERMANTO",
  },
  {
    nis: 1037,
    name: "Ahmad Asyrofu Wildan",
    class_id: 2,
    room_id: 5,
    district: "TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "3/16/2006",
    guardian: "PANJI",
  },
  {
    nis: 1038,
    name: "Ananda Rifky",
    class_id: 2,
    room_id: 5,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "7/18/2006",
    guardian: "NANA",
  },
  {
    nis: 1039,
    name: "Dava Pratama",
    class_id: 2,
    room_id: 5,
    district: "TANGERANG SELATAN",
    birthplace: "JAKARTA",
    birthdate: "9/10/2005",
    guardian: "YUSNIAH",
  },
  {
    nis: 1040,
    name: "Fahmi Al Hafidz",
    class_id: 2,
    room_id: 8,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "12/13/2005",
    guardian: "SUTISNA",
  },
  {
    nis: 1041,
    name: "Farel Ahmad Rayhan",
    class_id: 2,
    room_id: 5,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "5/29/2006",
    guardian: "KALEMI",
  },
  {
    nis: 1042,
    name: "Fariz Sayyid Assabiq",
    class_id: 2,
    room_id: 5,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "4/14/2006",
    guardian: "LISA",
  },
  {
    nis: 1043,
    name: "Haikal Satria",
    class_id: 2,
    room_id: 5,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "7/26/2006",
    guardian: "KHODIJAH",
  },
  {
    nis: 1044,
    name: "Ilyasa",
    class_id: 2,
    room_id: 8,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "4/6/2006",
    guardian: "IKAH MARDIAHNA",
  },
  {
    nis: 1045,
    name: "Mohammad Afreza Attar",
    class_id: 2,
    room_id: 8,
    district: "TANGERANG SELATAN",
    birthplace: "SAMPIT",
    birthdate: "4/12/2005",
    guardian: "FENTY",
  },
  {
    nis: 1046,
    name: "Mu'amar Zaka Nurmustofa",
    class_id: 2,
    room_id: 8,
    district: "TANGERANG",
    birthplace: "BANJARNEGARA",
    birthdate: "12/23/2006",
    guardian: "HADI",
  },
  {
    nis: 1047,
    name: "Muh. Maulana Faqih",
    class_id: 2,
    room_id: 7,
    district: "JAKARTA SEL",
    birthplace: "JAKARTA",
    birthdate: "4/16/2006",
    guardian: "NISA",
  },
  {
    nis: 1048,
    name: "Muhammad Al Raziq Wilson Angkat Sutan",
    class_id: 2,
    room_id: 5,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "2/4/2006",
    guardian: "AGUS SRI WIYANTI",
  },
  {
    nis: 1049,
    name: "Muhammad Fadhli",
    class_id: 2,
    room_id: 7,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "8/13/2005",
    guardian: "ASNAH",
  },
  {
    nis: 1050,
    name: "Muhammad Hafiz Alawi",
    class_id: 2,
    room_id: 4,
    district: "TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "3/12/2006",
    guardian: "ABDUL MANAN",
  },
  {
    nis: 1051,
    name: "Muhammad Rafa Mulya",
    class_id: 2,
    room_id: 4,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "10/6/2006",
    guardian: "KHAIRUL",
  },
  {
    nis: 1052,
    name: "Muhammad Ridhwan Rahmaandani",
    class_id: 2,
    room_id: 6,
    district: "TANGERANG SELATAN",
    birthplace: "SRAGEN",
    birthdate: "10/13/2004",
    guardian: "SUTOMI",
  },
  {
    nis: 1053,
    name: "Muhammad Rizky Wahyudi",
    class_id: 2,
    room_id: 7,
    district: "TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "4/10/2006",
    guardian: "YULI",
  },
  {
    nis: 1054,
    name: "Muhammad Sobri",
    class_id: 2,
    room_id: 7,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "1/2/2006",
    guardian: "ILZAM",
  },
  {
    nis: 1055,
    name: "Ramdhan Fikri Setiawan",
    class_id: 2,
    room_id: 6,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG SELATAN",
    birthdate: "10/8/2005",
    guardian: "SAVITRI SARI",
  },
  {
    nis: 1056,
    name: "Reza Rama Putra",
    class_id: 2,
    room_id: 8,
    district: "JAKARTA UTARA",
    birthplace: "JAKARTA",
    birthdate: "12/1/2004",
    guardian: "SITI MUNIROH",
  },
  {
    nis: 1057,
    name: "Ridho Abdul Hafiz",
    class_id: 2,
    room_id: 3,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "6/25/2006",
    guardian: "SALBIYAH",
  },
  {
    nis: 1058,
    name: "Risyat Nur Sya'bani",
    class_id: 2,
    room_id: 4,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "9/2/2006",
    guardian: "AZHARI",
  },
  {
    nis: 1059,
    name: "Syahirsyah Wafiy Azhani",
    class_id: 2,
    room_id: 4,
    district: "TANGERANG SELATAN",
    birthplace: "GARUT",
    birthdate: "9/23/2006",
    guardian: "ASEP AZHAR",
  },
  {
    nis: 1060,
    name: "Tahmid Tohir Hartono",
    class_id: 2,
    room_id: 8,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "7/23/2004",
    guardian: "TINTIN",
  },
  {
    nis: 1061,
    name: "Tubagus Arifin Zahid",
    class_id: 2,
    room_id: 3,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "6/18/2005",
    guardian: "SRI HARTONO",
  },
  {
    nis: 1062,
    name: "Yasir Malik Abidillah",
    class_id: 2,
    room_id: 3,
    district: "TANGERANG SELATAN",
    birthplace: "DEPOK",
    birthdate: "5/23/2006",
    guardian: "SITI ROMIYATI",
  },
  {
    nis: 1063,
    name: "ILARIUS REKON",
    class_id: 2,
    room_id: 3,
    district: "MENTAWAI",
    birthplace: "MENTAWAI",
    birthdate: "6/9/2005",
    guardian: "AZIZAH",
  },
  {
    nis: 1064,
    name: "ABDUL AZIZ",
    class_id: 3,
    room_id: 5,
    district: "BEKASI",
    birthplace: "TANGERANG",
    birthdate: "9/21/2004",
    guardian: "ABDUL BASRI",
  },
  {
    nis: 1065,
    name: "AKHDAAN SALDIANSYAH",
    class_id: 3,
    room_id: 10,
    district: "BOGOR",
    birthplace: "JAKARTA",
    birthdate: "1/9/2005",
    guardian: "DIANSOMMY",
  },
  {
    nis: 1066,
    name: "ARYA SAPUTRA",
    class_id: 3,
    room_id: 5,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG SELATAN",
    birthdate: "6/12/2005",
    guardian: "KAMILAH",
  },
  {
    nis: 1067,
    name: "DWI FEBRI ARBIYANSA",
    class_id: 3,
    room_id: 1,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "2/27/2005",
    guardian: "MARYANIH",
  },
  {
    nis: 1068,
    name: "HARYO KURNIAWAN AHMAD MUBAROK",
    class_id: 3,
    room_id: 1,
    district: "JAKARTA BARAT",
    birthplace: "BOGOR",
    birthdate: "10/9/2004",
    guardian: "HARNO",
  },
  {
    nis: 1069,
    name: "HISYAM HANIF",
    class_id: 3,
    room_id: 10,
    district: "JAKARTA BARAT",
    birthplace: "JAKARTA",
    birthdate: "1/14/2005",
    guardian: "SUBHAN",
  },
  {
    nis: 1070,
    name: "LUQMAN SYAKIR",
    class_id: 3,
    room_id: 1,
    district: "TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "8/25/2005",
    guardian: "SOPYAN",
  },
  {
    nis: 1071,
    name: "M. CLAUDYO",
    class_id: 3,
    room_id: 10,
    district: "PADANG",
    birthplace: "BUKIT TINGGI",
    birthdate: "7/22/2005",
    guardian: "YULITA",
  },
  {
    nis: 1072,
    name: "MOCH. AIKHAL AYATULLAH HUSAINY",
    class_id: 3,
    room_id: 1,
    district: "TANGERANG",
    birthplace: "SUKA BUMI",
    birthdate: "10/31/2004",
    guardian: "HASAN",
  },
  {
    nis: 1073,
    name: "MUHAMMAD ARDHI ZAHRAN",
    class_id: 3,
    room_id: 9,
    district: "TANGERANG SELATAN",
    birthplace: "JAKARTA",
    birthdate: "3/17/2005",
    guardian: "RAYNI",
  },
  {
    nis: 1074,
    name: "MUHAMMAD IKHYA RAMADHAN",
    class_id: 3,
    room_id: 1,
    district: "TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "10/31/2004",
    guardian: "SULAIMAN",
  },
  {
    nis: 1075,
    name: "MUHAMMAD AMMAR ROZAN",
    class_id: 3,
    room_id: 9,
    district: "TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "8/2/2005",
    guardian: "ASIH",
  },
  {
    nis: 1076,
    name: "MUHAMMAD BINTANG ALFANSYAH",
    class_id: 3,
    room_id: 8,
    district: "TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "12/24/2005",
    guardian: "PULANG",
  },
  {
    nis: 1077,
    name: "MUHAMMAD GILANG ALFANOSY",
    class_id: 3,
    room_id: 1,
    district: "TANGERANG SELATAN",
    birthplace: "JAKARTA SELATAN",
    birthdate: "11/16/2005",
    guardian: "FATMAWATI",
  },
  {
    nis: 1078,
    name: "MUHAMMAD HADID YUDISTIRA",
    class_id: 3,
    room_id: 8,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "2/15/2005",
    guardian: "WULANDARI",
  },
  {
    nis: 1079,
    name: "MUHAMMAD RAHMAN NUR ROHIM",
    class_id: 3,
    room_id: 9,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "3/19/2005",
    guardian: "HARDIANSYAH",
  },
  {
    nis: 1080,
    name: "MUHAMMAD RAJA GOZI",
    class_id: 3,
    room_id: 5,
    district: "BENGKULU",
    birthplace: "BENGKULU",
    birthdate: "7/2/2005",
    guardian: "YULIZARNI",
  },
  {
    nis: 1081,
    name: "MUHAMMAD RANDI ISLAMI",
    class_id: 3,
    room_id: 1,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "3/20/2005",
    guardian: "ANSORY",
  },
  {
    nis: 1082,
    name: "MUHAMMAD RASYID HABIBI",
    class_id: 3,
    room_id: 8,
    district: "PALEMBANG",
    birthplace: "PALEMBANG",
    birthdate: "3/7/2006",
    guardian: "SUPRANTI",
  },
  {
    nis: 1083,
    name: "MUHAMMAD RIVAN PUTRA SUHERMAN",
    class_id: 3,
    room_id: 10,
    district: "JAKARTA UTARA",
    birthplace: "JAKARTA",
    birthdate: "1/24/2005",
    guardian: "JONI SUHERMAN",
  },
  {
    nis: 1084,
    name: "NAFIO ARTIN MAULANA",
    class_id: 3,
    room_id: 8,
    district: "TANGERANG SELATAN",
    birthplace: "JAKARTA",
    birthdate: "4/6/2005",
    guardian: "MARTIN",
  },
  {
    nis: 1085,
    name: "NAUVAL RAHMAYADI",
    class_id: 3,
    room_id: 10,
    district: "TANGERANG",
    birthplace: "PANDEGELANG",
    birthdate: "9/6/2004",
    guardian: "NOVI",
  },
  {
    nis: 1086,
    name: "RIZLIANSYAH ARKAN",
    class_id: 3,
    room_id: 1,
    district: "TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "5/27/2005",
    guardian: "UNTUNG SAJOKO",
  },
  {
    nis: 1087,
    name: "SATRIA BUANA",
    class_id: 3,
    room_id: 10,
    district: "TANGERANG SELATAN",
    birthplace: "LUBUK LINGGAU",
    birthdate: "12/24/2004",
    guardian: "SAGI SALIM",
  },
  {
    nis: 1088,
    name: "VIKRA MEYPA ARPAN",
    class_id: 3,
    room_id: 5,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "5/27/2004",
    guardian: "KASMAN",
  },
  {
    nis: 1089,
    name: "ZULMAHDI",
    class_id: 3,
    room_id: 1,
    district: "JAMBI",
    birthplace: "RANTAUNGARAU",
    birthdate: "3/2/2002",
    guardian: "RAMLAH",
  },
  {
    nis: 1090,
    name: "ADRIAN ALFAREZI",
    class_id: 4,
    room_id: 9,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG SELATAN",
    birthdate: "4/14/2005",
    guardian: "",
  },
  {
    nis: 1091,
    name: "ALIF DIDAN ARFAKHSYAD",
    class_id: 4,
    room_id: 9,
    district: "JAMBI",
    birthplace: "MUARA BUNGO",
    birthdate: "5/5/2005",
    guardian: "DINDA SABRINA",
  },
  {
    nis: 1092,
    name: "ALYSYAH SEPTYAN PUTRA",
    class_id: 4,
    room_id: 1,
    district: "TANGERANG SELATAN",
    birthplace: "WONOGIRI",
    birthdate: "9/21/2004",
    guardian: "ACHDYAT IMANSYAH",
  },
  {
    nis: 1093,
    name: "AZRIAL DHIFANO RASYA",
    class_id: 4,
    room_id: 5,
    district: "JAKARTA SELATAN",
    birthplace: "JAKARTA SELATAN",
    birthdate: "12/6/2004",
    guardian: "BAMBANG",
  },
  {
    nis: 1094,
    name: "DIMAS RADITYA SAKIM",
    class_id: 4,
    room_id: 5,
    district: "SEMARANG",
    birthplace: "JAWA TENG",
    birthdate: "4/16/2006",
    guardian: "SAKIM",
  },
  {
    nis: 1095,
    name: "FADHLAN RAMADHAN",
    class_id: 4,
    room_id: 9,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG SELATAN",
    birthdate: "9/23/2005",
    guardian: "FARHAD",
  },
  {
    nis: 1096,
    name: "MUHAMMAD RIFKY MUSYAFFA",
    class_id: 4,
    room_id: 7,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG SELATAN",
    birthdate: "5/26/2004",
    guardian: "HENNY",
  },
  {
    nis: 1097,
    name: "MUHAMMAD AL-GHIFARI",
    class_id: 4,
    room_id: 1,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG SELATAN",
    birthdate: "3/6/2005",
    guardian: "TEGUH",
  },
  {
    nis: 1098,
    name: "MUHAMMAD BAYU ILHAM PANGESTU",
    class_id: 4,
    room_id: 9,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG SELATAN",
    birthdate: "3/16/2005",
    guardian: "TUNINGSIH",
  },
  {
    nis: 1099,
    name: "MUHAMMAD FADILLAH",
    class_id: 4,
    room_id: 10,
    district: "JAKARTA SELATAN",
    birthplace: "JAKARTA",
    birthdate: "3/10/2005",
    guardian: "BAMBANG",
  },
  {
    nis: 1100,
    name: "MUHAMMAD FAHMI ALIYANSYAH",
    class_id: 4,
    room_id: 6,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG SELATAN",
    birthdate: "7/10/2005",
    guardian: "SITI ASIAH",
  },
  {
    nis: 1101,
    name: "MUHAMMAD NUR ILHAM",
    class_id: 4,
    room_id: 1,
    district: "JAKARTA PUSAT",
    birthplace: "JAKARTA PUSAT",
    birthdate: "3/10/2005",
    guardian: "NUR ARIFIN",
  },
  {
    nis: 1102,
    name: "MUHAMMAD RIDWAN RENALDI",
    class_id: 4,
    room_id: 9,
    district: "JAKARTA BARAT",
    birthplace: "JAKARTA",
    birthdate: "5/6/2005",
    guardian: "SUJANA",
  },
  {
    nis: 1103,
    name: "PASHA HILMIY ISMAIL",
    class_id: 4,
    room_id: 1,
    district: "JAKARTA BARAT",
    birthplace: "JAKARTA",
    birthdate: "1/20/2005",
    guardian: "SURYADARMA",
  },
  {
    nis: 1104,
    name: "RAFAEL GHANI PUTRA FARHAN",
    class_id: 4,
    room_id: 6,
    district: "BEKASI",
    birthplace: "JAKARTA",
    birthdate: "3/16/2005",
    guardian: "FARHAN",
  },
  {
    nis: 1105,
    name: "RAHMAD HABIB OKTAZA PUTRA",
    class_id: 4,
    room_id: 9,
    district: "BENGKULU",
    birthplace: "BENGKULU",
    birthdate: "11/7/2004",
    guardian: "OKLAN",
  },
  {
    nis: 1106,
    name: "RIZQI MUHAMMAD IKHSAN",
    class_id: 4,
    room_id: 3,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG SELATAN",
    birthdate: "2/14/2005",
    guardian: "IHSANNUDIN",
  },
  {
    nis: 1107,
    name: "SA'BAN INDRA MAULANA",
    class_id: 4,
    room_id: 9,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG SELATAN",
    birthdate: "9/18/2005",
    guardian: "JAKA",
  },
  {
    nis: 1108,
    name: "SADDAM FAADHIL GHAIYYAS",
    class_id: 4,
    room_id: 6,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "8/29/2005",
    guardian: "ADNAN SUGUHARTO",
  },
  {
    nis: 1109,
    name: "SAKTIKA PINILIH PUTRANTO",
    class_id: 4,
    room_id: 6,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "8/19/2005",
    guardian: "ISMUNAWAN",
  },
  {
    nis: 1110,
    name: "SOFWAN",
    class_id: 4,
    room_id: 9,
    district: "RANTAU NGARAU",
    birthplace: "JAMBI",
    birthdate: "8/24/2004",
    guardian: "KHIDIR",
  },
  {
    nis: 1111,
    name: "TUBAGUS AHMAD FADLI ARYADILLAH",
    class_id: 4,
    room_id: 1,
    district: "SERANG",
    birthplace: "SERANG",
    birthdate: "12/28/2004",
    guardian: "TB.AHMAD FAISAL",
  },
  {
    nis: 1112,
    name: "YUSUF ADITHYA",
    class_id: 4,
    room_id: 10,
    district: "TANGERANG KOTA",
    birthplace: "TANGERANG",
    birthdate: "7/31/2005",
    guardian: "IKA TANTI SARI",
  },
  {
    nis: 1113,
    name: "ZULFAN KHAIRIL ANAM",
    class_id: 4,
    room_id: 1,
    district: "KABUPATEN TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "8/10/2005",
    guardian: "M. SAID",
  },
  {
    nis: 1114,
    name: "ABDULLAH AHMAD ALKAF",
    class_id: 5,
    room_id: 9,
    district: "JAKARTA TIMUR",
    birthplace: "JAKARTA",
    birthdate: "9/19/2004",
    guardian: "HABIB AHMAD ALKAF",
  },
  {
    nis: 1115,
    name: "AGUM RIJAL AINALYAQIN",
    class_id: 5,
    room_id: 10,
    district: "JAKARTA SELATAN",
    birthplace: "KUDUS",
    birthdate: "4/23/2003",
    guardian: "",
  },
  {
    nis: 1116,
    name: "AHMAD GHOZALI DA SILVA",
    class_id: 5,
    room_id: 1,
    district: "DILI",
    birthplace: "DILI",
    birthdate: "4/25/2004",
    guardian: "BOAVANTURA",
  },
  {
    nis: 1117,
    name: "ARKAN AHMAD SUIAFI",
    class_id: 5,
    room_id: 9,
    district: "JAKARTA SELATAN",
    birthplace: "JAKARTA",
    birthdate: "7/13/2004",
    guardian: "M. NUR UHUSUM",
  },
  {
    nis: 1118,
    name: "DIAZ CESARIO RIO",
    class_id: 5,
    room_id: 10,
    district: "TANGERANG",
    birthplace: "JAKARTA",
    birthdate: "5/29/2004",
    guardian: "MULYADI",
  },
  {
    nis: 1119,
    name: "FATHI RIZQI RAMADON",
    class_id: 5,
    room_id: 7,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "11/14/2003",
    guardian: "SURYA",
  },
  {
    nis: 1120,
    name: "FERDI ANZAMI SISWADI",
    class_id: 5,
    room_id: 1,
    district: "BOGOR",
    birthplace: "TANGERANG",
    birthdate: "10/24/2003",
    guardian: "HERISISMADI",
  },
  {
    nis: 1121,
    name: "GUSTY ERLANGGA PUTRA",
    class_id: 5,
    room_id: 10,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "12/1/2003",
    guardian: "DEWI",
  },
  {
    nis: 1122,
    name: "HADI FAJAR ROMANSYAH",
    class_id: 5,
    room_id: 2,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "10/30/2003",
    guardian: "BAHRUDIN",
  },
  {
    nis: 1123,
    name: "JERYCO FEBRIAN",
    class_id: 5,
    room_id: 2,
    district: "TANGERANG SELATAN",
    birthplace: "",
    birthdate: "",
    guardian: "",
  },
  {
    nis: 1124,
    name: "LISTYO CAKRA AQNI",
    class_id: 5,
    room_id: 2,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "1/18/2004",
    guardian: "SUYONO",
  },
  {
    nis: 1125,
    name: "MOCHTAR LUTHFI ALHUSORI",
    class_id: 5,
    room_id: 2,
    district: "TANGERANG",
    birthplace: "JAKARTA",
    birthdate: "7/5/2004",
    guardian: "ENDANG",
  },
  {
    nis: 1126,
    name: "MUHAMAD AFIV ZAFIERSYAH",
    class_id: 5,
    room_id: 10,
    district: "JAKARTA BARAT",
    birthplace: "JAKARTA",
    birthdate: "12/25/2004",
    guardian: "SITI RAHMAN",
  },
  {
    nis: 1127,
    name: "MUHAMAD FAZA AL FARABI",
    class_id: 5,
    room_id: 2,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "8/31/2004",
    guardian: "SANUSI",
  },
  {
    nis: 1128,
    name: "MUHAMMAD ABDUL AZIZ",
    class_id: 5,
    room_id: 6,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "5/13/2004",
    guardian: "ROHIDI",
  },
  {
    nis: 1129,
    name: "MUHAMMAD FAHMI",
    class_id: 5,
    room_id: 1,
    district: "JAKARTA SELATAN",
    birthplace: "JAWA TENG",
    birthdate: "12/1/2003",
    guardian: "NURJANAH",
  },
  {
    nis: 1130,
    name: "MUHAMMAD FUAD ALWI",
    class_id: 5,
    room_id: 2,
    district: "TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "7/10/2004",
    guardian: "MULAN JAMILAH",
  },
  {
    nis: 1131,
    name: "MUHAMMAD RAJWA AS'AD",
    class_id: 5,
    room_id: 7,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "7/6/2003",
    guardian: "IMAM WAHYUDI",
  },
  {
    nis: 1132,
    name: "MUHAMMAD ZULHUDA",
    class_id: 5,
    room_id: 1,
    district: "BATAM",
    birthplace: "BATAM",
    birthdate: "11/18/2003",
    guardian: "ANEUK DARA MEUTIA",
  },
  {
    nis: 1133,
    name: "RAFLI MUHAMMAD UBAID AL-RAHMAN",
    class_id: 5,
    room_id: 9,
    district: "KARAWANG",
    birthplace: "KARAWANG",
    birthdate: "4/25/2004",
    guardian: "UBAIDILLAH",
  },
  {
    nis: 1134,
    name: "RAYYAN MUBARAK YAPONO",
    class_id: 5,
    room_id: 2,
    district: "JAKARTA SELATAN",
    birthplace: "KUALA LUMPUR",
    birthdate: "11/24/2004",
    guardian: "YAPONO",
  },
  {
    nis: 1135,
    name: "PRASETYO ANANTA",
    class_id: 5,
    room_id: 7,
    district: "BOGOR",
    birthplace: "RIAU",
    birthdate: "10/25/2002",
    guardian: "MISTANTINA",
  },
  {
    nis: 1136,
    name: "A. MUH IMAM HAIDIR",
    class_id: 6,
    room_id: 7,
    district: "",
    birthplace: "MAKASSAR",
    birthdate: "",
    guardian: "",
  },
  {
    nis: 1137,
    name: "ALENDRA NURMALIK IBRAHIM",
    class_id: 6,
    room_id: 2,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG SELATAN",
    birthdate: "3/13/2004",
    guardian: "WITA",
  },
  {
    nis: 1138,
    name: "ALIF FAUZAN YAHYA",
    class_id: 6,
    room_id: 3,
    district: "TANGERANG SELATAN",
    birthplace: "JAKARTA",
    birthdate: "9/3/2004",
    guardian: "ARET",
  },
  {
    nis: 1139,
    name: "ALIFANDI FAKHRUDIN AFIF",
    class_id: 6,
    room_id: 2,
    district: "TANGERANG",
    birthplace: "JAKARTA",
    birthdate: "7/23/2004",
    guardian: "SUGENG RIADI",
  },
  {
    nis: 1140,
    name: "ARYO KALIMASADA",
    class_id: 6,
    room_id: 4,
    district: "TANGERANG",
    birthplace: "TANGERANG",
    birthdate: "12/25/2003",
    guardian: "A. ZAINUDIN",
  },
  {
    nis: 1141,
    name: "BAYU PRAYOGA AL-FATTAH",
    class_id: 6,
    room_id: 4,
    district: "TANGERANG SELATAN",
    birthplace: "YOGKARTA",
    birthdate: "4/19/2004",
    guardian: "EKO.S.N",
  },
  {
    nis: 1142,
    name: "DAFFA FACHRI AKBAR",
    class_id: 6,
    room_id: 2,
    district: "TANGERANG",
    birthplace: "DEPOK",
    birthdate: "8/11/2004",
    guardian: "TEGUH",
  },
  {
    nis: 1143,
    name: "DAFA HADYAN SHEHAN",
    class_id: 6,
    room_id: 7,
    district: "BEKASI",
    birthplace: "BEKASI",
    birthdate: "1/9/2004",
    guardian: "ANDRI",
  },
  {
    nis: 1144,
    name: "DIMAS ARYA FADILAH",
    class_id: 6,
    room_id: 10,
    district: "TANGERANG",
    birthplace: "TANGERANG SELATAN",
    birthdate: "11/1/2004",
    guardian: "ATIH",
  },
  {
    nis: 1145,
    name: "DIMAS FATIHURRIZKY",
    class_id: 6,
    room_id: 4,
    district: "DEPOK",
    birthplace: "DEPOK",
    birthdate: "8/11/2003",
    guardian: "H. ADE MUNADI",
  },
  {
    nis: 1146,
    name: "EKA SATRIA APRIAN",
    class_id: 6,
    room_id: 4,
    district: "TANGERANG SELATAN",
    birthplace: "SRAGEN",
    birthdate: "4/22/2004",
    guardian: "PURWANTI",
  },
  {
    nis: 1147,
    name: "ILHAM NUR SIDIQ",
    class_id: 6,
    room_id: 2,
    district: "TANGERANG SELATAN",
    birthplace: "JAKARTA",
    birthdate: "6/18/2004",
    guardian: "NUNUNG",
  },
  {
    nis: 1148,
    name: "ISFAN AHMAD BAIHAQI",
    class_id: 6,
    room_id: 2,
    district: "JAKARTA",
    birthplace: "JAKARTA",
    birthdate: "9/29/2003",
    guardian: "ICHSANI",
  },
  {
    nis: 1149,
    name: "MOHAMAD EXSANUDIN FAJAR",
    class_id: 6,
    room_id: 2,
    district: "OKU TIMUR",
    birthplace: "OKU TIMUR",
    birthdate: "2/19/2005",
    guardian: "TOHA",
  },
  {
    nis: 1150,
    name: "MUHAMAD ABDUL RISKY",
    class_id: 6,
    room_id: 3,
    district: "",
    birthplace: "",
    birthdate: "",
    guardian: "",
  },
  {
    nis: 1151,
    name: "MUHAMAD SATRIA HAKIM",
    class_id: 6,
    room_id: 1,
    district: "",
    birthplace: "TANGERANG SELATAN",
    birthdate: "",
    guardian: "",
  },
  {
    nis: 1152,
    name: "MUHAMMAD ADIYA PUTRA",
    class_id: 6,
    room_id: 2,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG",
    birthdate: "5/3/2004",
    guardian: "KARTINA ALIE",
  },
  {
    nis: 1153,
    name: "MUHAMMAD FARHAN SHOLAHUDIN",
    class_id: 6,
    room_id: 4,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG SELATAN",
    birthdate: "4/6/2004",
    guardian: "ATIYAH",
  },
  {
    nis: 1154,
    name: "MUHAMMAD TEGAR DWI NURRAHMAN",
    class_id: 6,
    room_id: 10,
    district: "JAKARTA",
    birthplace: "JAKARTA",
    birthdate: "8/31/2003",
    guardian: "SUGENG",
  },
  {
    nis: 1155,
    name: "RAKHA AJI PERMANA",
    class_id: 6,
    room_id: 2,
    district: "CIGANJUR",
    birthplace: "JAKARTA",
    birthdate: "6/20/2003",
    guardian: "UJANG",
  },
  {
    nis: 1156,
    name: "SATRIO BAGUS WICAKSONO",
    class_id: 6,
    room_id: 1,
    district: "TANGERANG SELATAN",
    birthplace: "TANGERANG SELATAN",
    birthdate: "8/11/2004",
    guardian: "KASAN SUJIONO",
  },
  {
    nis: 1157,
    name: "SULTHON MALIK",
    class_id: 6,
    room_id: 2,
    district: "DEPOK",
    birthplace: "DEPOK",
    birthdate: "4/22/2004",
    guardian: "NUCHRO",
  },
  {
    nis: 1158,
    name: "WILDAN AZRILYANSYAH",
    class_id: 6,
    room_id: 4,
    district: "",
    birthplace: "",
    birthdate: "",
    guardian: "",
  },
  {
    nis: 1159,
    name: "YAZID KAMIL",
    class_id: 6,
    room_id: 2,
    district: "JAKARTA",
    birthplace: "JAKARTA",
    birthdate: "4/19/2004",
    guardian: "MUNAWIR",
  },
];
